### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by wolframhaussig** [screeps/ide#10]
Hi,

Despite using VS Code for a while now I would be willing to switch to ATOM if I could use this IDE plugin but it seems that this project is abandoned, right? There was no commit since 2019 and none of the issues here have been solved.

Best regards
Wolfram

**Comment by dmitriyff** [comment]
Hi, this project still alive, but now all our forces are focus on another parts of Screeps.
In the future, we will continue to improve IDE plugin.

**Comment by mhindman** [comment]
Can you at least fix the issue where it won't save? it basically makes it un-usable.
